import { Url } from "url";

export  const List = [
    {
      Project_Title: 'Codetake',
      Version_num: '0.01',
      Description: "This is an app that will allow one to show off their apps/web apps and show their features, languages, frameworks, and techniques used to build it using tags. By means of these tags, users can find and group projects. Users can also share their issues with the creator and others so that their issues could be resolved by either the creator or other users. The creator can also share what changes they've made with each update and share when the update/commit was commit",
      Categories: [ 'react', 'FaunaDB', 'localStorage', 'sessionStorage' ],
      Changes: 'Hopefully will be able to save projects to database.',
      Roadmap: [ 'none', 'Testing purposes only' ],
      Creator: 'Alonzo Austin',
      Id: 268305773758513660,
      Update: [ [Object] ],
      Repository: '',
      Links: [],
      inquisitors: []
    },
    {
      Project_Title: 'Treasure Store',
      Version_num: '0.01',
      Description: 'Though it is a personal project of mine, there are two versions that have been created, one using regular nodejs (with ejs as the view engine and MongoDB) and the other using nextjs (using localStorage). It allows me to view Biblical scriptures that I appreciate and allows me to take notes based on how they help me, what I learn from it, how it increases my faith, what I learn about Jehovah, and how I can use this to help others.',
      Categories: [ 'Nextjs', 'localStorage', 'port' ],
      Changes: 'Added to codetake',
      Roadmap: [],
      Id: 268405961362768420,
      Creator: 'Alonzo Austin',
      Update: [ [Object], [Object] ],
      Repository: 'https://github.com/glowtoad123/treasure-store',
      Links: [],
      inquisitors: []
    },
    {
      Project_Title: 'EJS Challenge',
      Version_num: '1.0',
      Creator: 'Alonzo Austin',
      Description: 'This was a blog post project that I had to do when taking that online udemy course.',
      Categories: [ 'Nodejs', 'MongoDB', 'EJS' ],
      Changes: 'Finished',
      Roadmap: [ 'Maybe some experimentation' ],
      Id: 268408016551805470,
      Update: [ [Object] ],
      Repository: '',
      Links: [],
      inquisitors: []
    },
    {
      Project_Title: 'react-keeper',
      Version_num: '1.0',
      Description: 'This is a veeeery basic notes app created using react as a class project. ',
      Categories: [ 'react', 'basic' ],
      Changes: 'submission',
      Creator: 'Alonzo Austin',
      Roadmap: [ 'deletion' ],
      Update: [ [Object] ],
      Repository: '',
      Links: [],
      inquisitors: []
    },
    {
      Project_Title: 'Codentake',
      Version_num: '0.02',
      Description: 'A webapp that will allow users to display their projects and what techniques, frameworks, and languages they used',
      Categories: [ 'react', 'Nextjs', 'localStorage', 'SPA', 'hooks', 'FaunaDB' ],
      Changes: 'Made the components into pages.',
      Roadmap: [
        'Add the ability to add projects to your favorties',
        'Add the ability to be notified when a developer updates his project',
        'Add the ability to make suggestions and issues on other developers projects'
      ],
      Creator: 'Alonzo Austin',
      Update: [ [Object], [Object], [Object], [Object] ],
      Repository: 'https://github.com/glowtoad123/codentake',
      Links: [ 'https://codentake.vercel.app' ],
      inquisitors: []
    },
    {
      Project_Title: 'sample app',
      Version_num: '0',
      Description: "This is a non existent app made with the purpose of testing to see whether or not the user's info will be posted to the database",
      Categories: [ 'testing' ],
      Changes: 'creation',
      Roadmap: [ 'deletion' ],
      Creator: 'sampleuser',
      Update: [ [Object] ],
      Repository: '',
      Links: [],
      inquisitors: []
    },
    {
      Project_Title: 'fasfsd',
      Version_num: '0',
      Description: 'fadsfhgsfads',
      Categories: [ 'test' ],
      Changes: 'asfsdfsfas',
      Roadmap: [ 'fasdfdsf' ],
      Creator: 'sampleuser',
      Update: [ [Object] ],
      Repository: '',
      Links: [],
      inquisitors: []
    },
    {
      Project_Title: 'Changed Test',
      Version_num: '1',
      Description: 'This is a test to see if the user name would appear on the project',
      Categories: [ 'testing' ],
      Changes: 'creation ',
      Roadmap: [ 'deletion' ],
      Creator: 'Alonzo Austin',
      Update: [ [Object] ],
      Repository: '',
      Links: [],
      inquisitors: []
    },
    {
      Project_Title: 'Sample 1',
      Version_num: '1',
      Description: 'siadfhdsifhfb d c  sdcdsj dsb  j  bds  jsd jicdscfcdfdscs   sdvdisvndsjc bdjsncdjscdjs c jsdc dsl sdj jslbvcds jsd djbv jdb dj',
      Categories: [ 'testing', 'purposes', 'only' ],
      Changes: 'Creation',
      Roadmap: [],
      Creator: 'auser',
      Update: [ [Object], [Object] ],
      Repository: '',
      Links: [],
      inquisitors: []
    },
    {
      Project_Title: 'Roadmap Test',
      Version_num: '1',
      Description: 'This is a test to see if the roadmap will return as an array instead of a string',
      Categories: [ 'testing' ],
      Changes: 'creation',
      Roadmap: [ 'futher Testing' ],
      Creator: 'Alonzo Austin',
      Update: [ [Object] ],
      Repository: '',
      Links: [],
      inquisitors: []
    },
    {
      Project_Title: 'updated post',
      Description: 'This is a test to see if the updated property will display in the database',
      Categories: [ 'testing' ],
      Roadmap: [],
      Repository: '',
      Creator: 'Alonzo Austin',
      Links: [],
      Update: { Version: '1.0', Changes: [Array] },
      inquisitors: []
    },
    {
      Project_Title: 'no project',
      Description: 'This is a placeholder under the "nothing account"',
      Categories: [ 'testing', 'accounts' ],
      Roadmap: [ 'Deletion' ],
      Repository: '',
      Creator: 'nothing',
      Links: [],
      Update: [ [Object] ],
      inquisitors: []
    },
    {
      Project_Title: 'Codentake (electron port)',
      Description: 'This is an electron port of codentake using nextron. This is a work in progress.',
      Categories: [ 'Port', 'Electron', 'react', 'nextjs', 'hooks' ],
      Roadmap: [],
      Repository: 'https://github.com/glowtoad123/codentake_nextron',
      Creator: 'Alonzo Austin',
      Links: [],
      Update: [ [Object], [Object], [Object] ],
      inquisitors: []
    },
    {
      Project_Title: 'Repository Check',
      Description: 'Originally I somehow forgot to add the ability to add a repository when creating a new project. This is a test so see if I the repository function will now work.',
      Categories: [ 'testing', 'test', 'repository' ],
      Roadmap: [],
      Repository: 'https://github.com/glowtoad123/repositorycheckrepositorydoesnotexist',
      Creator: 'Alonzo Austin',
      Links: [],
      Update: [ [Object] ],
      inquisitors: []
    }
  ]